/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router
//
// 小蜜蜂 Bee 菜单精简版：
//  - 企业 Agent 场景，一级导航只保留：项目 / 博主库 / 技能（暂合并知识库） / 管理员设置
//  - 老的聊天助手 / 知识库 / 余额充值 / 模型配置 等 hideInMenu=true 保留路由但不在菜单出现
//  - 如果未来需要整体下掉某个页面，直接 delete 掉对应 entry 即可。

import type { GeneratedRoute } from '@elegant-router/types'

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'agent-project-detail',
    path: '/agent-projects/:id',
    component: 'layout.base$view.agent-project-detail',
    props: true,
    meta: {
      title: 'agent-project-detail',
      i18nKey: 'route.agent-project-detail',
      hideInMenu: true,
      activeMenu: 'agent-projects'
    }
  },
  {
    name: 'agent-projects',
    path: '/agent-projects',
    component: 'layout.base$view.agent-projects',
    meta: {
      title: 'agent-projects',
      i18nKey: 'route.agent-projects',
      icon: 'solar:folder-with-files-bold-duotone',
      order: 1
    }
  },
  {
    name: 'chat',
    path: '/chat',
    component: 'layout.base$view.chat',
    meta: {
      title: 'chat',
      i18nKey: 'route.chat',
      icon: 'solar:chat-round-call-line-duotone',
      hideInMenu: true
    }
  },
  {
    name: 'chat-history',
    path: '/chat-history',
    component: 'layout.base$view.chat-history',
    meta: {
      title: 'chat-history',
      i18nKey: 'route.chat-history',
      roles: ['ADMIN'],
      icon: 'solar:hashtag-chat-bold-duotone',
      order: 96
    }
  },
  {
    name: 'creator-hub',
    path: '/creator-hub',
    component: 'layout.base$view.creator-hub',
    meta: {
      title: 'creator-hub',
      i18nKey: 'route.creator-hub',
      icon: 'solar:users-group-rounded-bold-duotone',
      order: 2
    }
  },
  {
    name: 'data-sources',
    path: '/data-sources',
    component: 'layout.base$view.data-sources',
    meta: {
      title: 'data-sources',
      i18nKey: 'route.data-sources',
      icon: 'solar:database-bold-duotone',
      roles: ['ADMIN'],
      order: 3
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'invite-code',
    path: '/invite-code',
    component: 'layout.base$view.invite-code',
    meta: {
      title: 'invite-code',
      i18nKey: 'route.invite-code',
      icon: 'solar:key-minimalistic-square-bold-duotone',
      roles: ['ADMIN'],
      order: 95
    }
  },
  {
    name: 'knowledge-base',
    path: '/knowledge-base',
    component: 'layout.base$view.knowledge-base',
    meta: {
      title: 'knowledge-base',
      i18nKey: 'route.knowledge-base',
      icon: 'solar:book-bookmark-bold-duotone',
      order: 3
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'model-provider',
    path: '/model-provider',
    component: 'layout.base$view.model-provider',
    meta: {
      title: 'model-provider',
      i18nKey: 'route.model-provider',
      icon: 'solar:tuning-square-bold-duotone',
      roles: ['ADMIN'],
      order: 93
    }
  },
  {
    name: 'org-tag',
    path: '/org-tag',
    component: 'layout.base$view.org-tag',
    meta: {
      title: 'org-tag',
      i18nKey: 'route.org-tag',
      icon: 'solar:tag-bold-duotone',
      roles: ['ADMIN'],
      order: 91
    }
  },
  {
    name: 'personal-center',
    path: '/personal-center',
    component: 'layout.base$view.personal-center',
    meta: {
      title: 'personal-center',
      i18nKey: 'route.personal-center',
      icon: 'solar:people-nearby-line-duotone',
      hideInMenu: true
    }
  },
  {
    name: 'recharge',
    path: '/recharge',
    component: 'layout.base$view.recharge',
    meta: {
      title: 'recharge',
      i18nKey: 'route.recharge',
      icon: 'solar:airbuds-case-charge-broken',
      hideInMenu: true
    }
  },
  {
    name: 'recharge-manage',
    path: '/recharge-manage',
    component: 'layout.base$view.recharge-manage',
    meta: {
      title: 'recharge-manage',
      i18nKey: 'route.recharge-manage',
      roles: ['ADMIN'],
      icon: 'solar:shop-minimalistic-broken',
      hideInMenu: true
    }
  },
  {
    name: 'usage-monitor',
    path: '/usage-monitor',
    component: 'layout.base$view.usage-monitor',
    meta: {
      title: 'usage-monitor',
      i18nKey: 'route.usage-monitor',
      icon: 'solar:chart-2-bold-duotone',
      roles: ['ADMIN'],
      order: 94
    }
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base$view.user',
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      icon: 'solar:users-group-two-rounded-bold-duotone',
      roles: ['ADMIN'],
      order: 90
    }
  },
  {
    name: 'xhs-cookies',
    path: '/xhs-cookies',
    component: 'layout.base$view.xhs-cookies',
    meta: {
      title: 'xhs-cookies',
      i18nKey: 'route.xhs-cookies',
      icon: 'solar:cookies-bold-duotone',
      roles: ['ADMIN'],
      hideInMenu: true,
      activeMenu: 'data-sources'
    }
  }
];
